### PR TITLE
Fix buffering in extractFile

### LINKED ISSUE #14: Fix buffering in zip.zipfiles.extractFile
At the moment it creates 1-character strings on each iteration:
https://github.com/nim-lang/zip/blob/1843ef1a108a4e3acbbc146a2c37a32273c5d8db/zip/zipfiles.nim#L163-L166

### PR DESCRIPTION
**Pull request by nigredo-tori**
Fixes #14

### CODE REVIEW

File: zip/zipfiles.nim [hunk 1]
```diff
@@ -159,11 +161,13 @@ iterator walkFiles*(z: var ZipArchive): string =
 
 proc extractFile*(z: var ZipArchive, srcFile: string, dest: Stream) =
   ## extracts a file from the zip archive `z` to the destination stream.
+  var buf: array[BufSize, byte]
   var strm = getStream(z, srcFile)
-  while true:
-    if not strm.atEnd:
-        dest.write(strm.readStr(1))
-    else: break
+  while not strm.atEnd:
```
Comment (Araq) [inline zip/zipfiles.nim]: Seems dangerous. If 'atEnd' is buggy and always returns false (infinite stream?) then this turns into an endless loop. Better to use

```nim
while true:
   let bytesRead = strm.readData(addr(buf[0]), buf.len)
   if bytesRead <= 0: break
   dest.writeData(addr(buf[0]), bytesRead)
```

**Comment by nigredo-tori** [comment]
Changed following @Araq's suggestion
